import Head from 'next/head';
import styles from '../src/components/Guide.module.css';

export default function Exchanges(){
 return <main className={styles.page}>
  <Head><title>Exchange funding · HOODLABS</title></Head>
  <nav><a href="/">← HOODLABS</a><a href="/guide#funding">Funding guide</a><a href="/security">Security</a></nav>
  <header><p className={styles.eyebrow}>KEEP EXCHANGE KEYS LOCAL</p><h1>Exchange → Ethereum ETH → Robinhood ETH.</h1><p>The website creates a public-address plan. The local companion talks directly to your exchange, so withdrawal credentials stay off HOODLABS.</p></header>
  <aside className={styles.contents} aria-label="Page contents"><a href="#path">Funding path</a><a href="#support">Exchange support</a><a href="#companion">Local companion</a><a href="#safety">Safety controls</a><a href="#status">Status</a></aside>
  <section id="path"><h2>Fund one wallet first</h2><ol><li>Create and restore-verify the node backup in HOODLABS.</li><li>Enter the source withdrawal amount in ETH. It is separate from the desired Robinhood balance.</li><li>Download the plan labelled <strong>Ethereum funding plan</strong>. It contains public addresses and amounts, never wallet keys.</li><li>Inspect and review one exchange withdrawal in the local companion.</li><li>After Ethereum ETH arrives, use the node’s Relay panel. Keep source gas, bridge once, verify completion, then check Robinhood ETH.</li></ol></section>
  <section id="support"><h2>Exchange support</h2><div className={styles.table}><table><thead><tr><th>Exchange</th><th>Supported connection</th><th>Check before use</th></tr></thead><tbody><tr><th>Binance</th><td>Read-only account and network checks. Withdraw manually.</td><td>Ethereum enabled, key permissions, whitelist, minimum, fees and Travel Rule. Binance.US is separate.</td></tr><tr><th>Kraken</th><td>Read checks and one reviewed withdrawal per destination when local live execution is enabled.</td><td>Approved address key, Ethereum method, amount semantics and fee.</td></tr><tr><th>OKX</th><td>Read-only account, network and balance checks. Withdraw manually.</td><td>Region/API host, permissions, destination, ETH-Ethereum network and fee.</td></tr></tbody></table></div><p>Published APIs do not guarantee access for each country or account. Never assume direct Robinhood withdrawals are supported.</p><details><summary>Official API references</summary><ul><li><a href="https://developers.binance.com/en/docs/catalog/core-trading-wallet/api/rest-api/capital" target="_blank" rel="noreferrer">Binance funding API</a></li><li><a href="https://docs.kraken.com/api-reference/funding/withdraw-funds" target="_blank" rel="noreferrer">Kraken withdrawal API</a></li><li><a href="https://www.okx.com/docs-v5/en/#funding-account-rest-api-withdrawal" target="_blank" rel="noreferrer">OKX funding API</a></li></ul></details></section>
  <section id="companion"><h2>Run the companion privately</h2><ol><li>Use Node 24 in Linux or WSL. Native Windows is currently unsupported.</li><li>Keep the journal in a private Linux home directory.</li><li>Set credentials only in the local process environment.</li><li>Follow the <a href="https://github.com/txc0ld/hoodlaunch/blob/main/docs/EXCHANGES.md" target="_blank" rel="noreferrer">reviewed local setup guide</a>.</li><li>Inspect with <code>node companion/cli.cjs inspect kraken funding-plan.json 1</code>. Use <code>binance</code> or <code>okx</code> for their read-only connectors.</li></ol><p>The companion has no web server. Local live withdrawals remain disabled until explicitly enabled after review.</p></section>
  <section id="safety"><h2>Controls that prevent a duplicate send</h2><ul><li>Use a dedicated API key, restricted IP and approved destinations where available. Grant only required permissions.</li><li>Never paste credentials into this website, support chat or a funding-plan file.</li><li>A timeout can happen after acceptance. The journal marks it unresolved and the companion does not resend automatically.</li><li>Reconcile an unresolved request at the exchange. Do not delete the journal to bypass protection.</li><li>Automatic funding allows one attempt per destination, including successful attempts. Make later top-ups manually.</li></ul></section>
  <section id="status"><h2>Where connection status appears</h2><p>The website has no exchange credentials and cannot report your account as connected. The local companion shows capability, fee and withdrawal results.</p><p>Mock tests cover request construction and failure handling. Your permissions, regional rules and any real withdrawal still need account-specific validation.</p></section>
 </main>;
}
export async function getServerSideProps(){return {props:{}};}
