import Head from 'next/head';
import styles from '../src/components/Guide.module.css';
import { HOODRICH_MINIMUM_FORMATTED } from '../src/lib/pro-access';

const inputs = [
 ['Name / ticker','Public display values. Tickers are not unique; identify a token by its contract address.'],
 ['Description','A public description up to 280 characters.'],
 ['Image','A public ipfs:// or https:// URI. Pro managed upload accepts still PNG, JPEG or WebP up to 4MB.'],
 ['Website / social','Optional public HTTPS links. Verify spelling before launch.'],
 ['Launch configuration','An enabled PONS configuration. Review supply, reserve, graduation threshold and fees.'],
 ['Pair asset','Native ETH or a PONS-approved ERC-20 address that passes factory, decimals and economics checks.'],
 ['Developer buy','Optional ETH for an ETH-paired launch. It is forced to zero for a custom pair.'],
 ['Fee recipient','Receives creator protocol payouts; defaults to the launch wallet. Verify the full address.'],
 ['Creator tax','Optional percentage within the current PONS cap. Disclose it clearly.'],
 ['Slippage','Maximum execution difference from the quote. HOODLABS caps launch and node-trade slippage at 2%.'],
 ['Buyback','Directs part of the creator fee share to PONS buybacks. Bought tokens vest gradually over five years under PONS rules; this is not a burn or price guarantee.'],
 ['Tax exemptions','Addresses excluded from opening snipe protection. Choose them at creation; they do not change supply.'],
];

export default function Guide(){
 return <main className={styles.page}>
  <Head><title>How to use HOODLABS · Plan, fund and launch</title><meta name="description" content="Plan token assumptions, prepare wallets, fund ETH, bridge to Robinhood Chain, and review a PONS launch." /></Head>
  <nav><a href="/">← HOODLABS</a><a href="/pro">Free vs Pro</a><a href="/security">Security</a></nav>
  <header><p className={styles.eyebrow}>THE HOODLABS GUIDE</p><h1>Plan first. Launch from one wallet. Expand carefully.</h1><p>Begin with the local Token Lab and one connected wallet. Verify the network, costs and recovery path before adding generated wallets.</p></header>
  <aside className={styles.contents} aria-label="Guide contents"><a href="#lab">1. Plan</a><a href="#wallets">2. Wallets</a><a href="#funding">3. Fund</a><a href="#bridge">4. Bridge</a><a href="#inputs">5. Configure</a><a href="#launch">6. Launch</a><a href="#trade">7. Trade</a><a href="#recovery">8. Recover</a></aside>

  <section id="lab"><h2>1. Model assumptions in Token Lab</h2><ol><li>Enter human token supply and a hypothetical USD price to see FDV.</li><li>Balance generic team, community, liquidity and treasury buckets to exactly 100%.</li><li>Enter your own buy or sell fee assumption to compare gross, fee and net token amounts.</li><li>With Pro, inspect linear vesting and save up to three local scenarios for CSV or JSON export.</li></ol><p><strong>Token Lab is planning only.</strong> It does not submit values to the launch form or make a market quote. PONS mints configured supply to its curve; the generic allocation and vesting models do not allocate or vest actual PONS tokens.</p></section>

  <section id="wallets"><h2>2. Prepare wallets</h2><p>Free launching uses your connected wallet. On iPhone, if Safari cannot find MetaMask, use the Connect instructions to open <strong>https://labs.hoodrich.rip/</strong> in MetaMask’s built-in browser and connect there. It is a separate browser workspace: unsaved Safari drafts and generated wallets do not transfer, and a protected preview may require Vercel sign-in again. A “node” here means a generated wallet address, not a blockchain validator.</p><ol><li>Sign in with your wallet or existing email account when the method is available. Wallet sign-in uses a message and costs no gas. Free accounts can generate one wallet every 24 hours; Pro supports up to 50 per attempt. Choose a backup password of 12–128 characters.</li><li>Generate wallets and download the encrypted backup.</li><li>Restore that file with the password. Matching addresses verify recovery. Funding and signing tools separately require Pro and live-tool availability.</li><li>Keep the backup offline, keep the password separately, and lock the session when finished.</li></ol><p>An accepted generation attempt uses the daily allowance even if you lose the backup. Retry an interrupted request in the same tab; it keeps the same request and wallets. Restoring a saved backup is always separate from the daily allowance.</p><p>One root backup controls all generated wallets. Multiple wallets create more gas, fees, records and chances for error; they do not create anonymity or independent investors. Inactivity locks the session after 15 minutes.</p></section>

  <section id="funding"><h2>3. Fund native ETH on Ethereum</h2><ol><li>Keep each verified node number beside its address.</li><li>At the exchange, choose ETH on Ethereum/ERC-20 network. Check minimum, fee, whitelist delay and regional rules.</li><li>Send a small test first.</li><li>Fund the bridge amount plus Ethereum gas. Later Robinhood transactions need native ETH on Robinhood Chain.</li></ol><p>The downloadable funding CSV is a balance plan, not an exchange instruction. API credentials belong only in the local companion. Binance and OKX connections are read-only; Kraken can prepare one reviewed withdrawal per destination when local execution is explicitly enabled.</p><p><a href="/exchanges">Exchange setup and status →</a></p></section>

  <section id="bridge"><h2>4. Bridge Ethereum ETH to Robinhood ETH</h2><ol><li>Select the funded node and enter the amount to bridge.</li><li>Request a Relay quote.</li><li>Verify source Ethereum chain 1, destination Robinhood Chain 4663, native ETH, recipient, minimum received and all costs.</li><li>Keep enough Ethereum ETH for gas, then submit once.</li><li>Recover status until completion and refresh Robinhood balances.</li></ol><p>This is a cross-chain transfer. WETH cannot pay native gas. Refresh an expired, unsubmitted quote; recover an unknown submitted bridge instead of sending again.</p></section>

  <section id="inputs"><h2>5. Configure the launch</h2><div className={styles.table}><table><thead><tr><th>Input</th><th>Meaning</th></tr></thead><tbody>{inputs.map(([name,meaning])=><tr key={name}><th scope="row">{name}</th><td>{meaning}</td></tr>)}</tbody></table></div><details><summary>Custom pair rules</summary><p>A custom ERC-20 address is not accepted blindly. PONS factory approval and the asset’s decimals and economics must validate. The pair is fixed at creation. Custom-pair launches force the initial developer buy to zero; launch fees and gas are still paid in native ETH. Later trades open through PONS. The generated-node trading engine supports ETH-paired launches only.</p></details><p>Live on-chain terms take precedence. See the <a href="https://docs.ponsfamily.com/v2" target="_blank" rel="noreferrer">official PONS V2 documentation</a>.</p></section>

  <section id="launch"><h2>6. Review and launch</h2><ol><li>Connect the creating wallet on Robinhood Chain and reserve native ETH for the launch fee and gas.</li><li>Complete public details, choose an enabled configuration and select the pair.</li><li>Select <strong>Review launch</strong>. Read the simulation, supply rules, exact spend, pair and fee recipient.</li><li>Approve the reviewed transaction in the wallet.</li><li>Wait for the required confirmations and verified token contract before continuing.</li></ol><p>If live launching is disabled, the screen is a preview. A local selection cannot bypass PONS eligibility, an unapproved pair or a disabled configuration. Do not edit and retry while submission status is unresolved.</p></section>

  <section id="trade"><h2>7. Buy or sell</h2><ol><li>Verify the full deployed token address and refresh balances.</li><li>For ETH pairs, choose a preset or enter a custom amount. Buy percentage uses spendable native ETH after gas; sell percentage uses token balance.</li><li>Buy max keeps an estimated gas reserve. Sell max still needs ETH for gas and may require a bounded approval.</li><li>For a custom pair, use the PONS trading link. Generated nodes and batch controls remain ETH-pair tools.</li><li>Wait for refreshed balances before another action.</li></ol><p>Quick buttons can submit after checks without a second dialog. Slippage does not remove price impact, protocol fees or gas. Several wallets do not create outside demand.</p></section>

  <section id="recovery"><h2>8. Stop and recover when status is unclear</h2><ul><li><strong>Insufficient ETH:</strong> check the chain and leave gas on that chain.</li><li><strong>Expired quote:</strong> request a fresh quote only if nothing was submitted.</li><li><strong>Pending or unknown:</strong> recover the recorded transaction and explorer status. Never clear history to force another send.</li><li><strong>Wrong network or runtime:</strong> stop and use a supported deployment.</li><li><strong>Wallets locked:</strong> restore the verified encrypted backup. Pending transactions remain pending.</li><li><strong>Pro unavailable:</strong> refresh account status. Paid access must be active; holder access needs a current session proof and at least {HOODRICH_MINIMUM_FORMATTED} $RICH in one wallet.</li><li><strong>Image rejected:</strong> use a public still PNG, JPEG or WebP under 4MB, or an existing public image URI.</li></ul><p><a href="/security">Read the full security and recovery limits before using significant funds.</a></p></section>
 </main>;
}
export async function getServerSideProps(){return {props:{}};}
