import Head from 'next/head';
import styles from '../src/components/Guide.module.css';
const fields = [
 ['Wallet count','How many separate wallet addresses to generate: 1–50. Each needs its own ETH for transactions.'],
 ['Backup password','Encrypts your downloaded wallet backup. Use 12–128 characters and keep the password separately. HOODLABS cannot reset it.'],
 ['Target ETH','The desired Robinhood Chain balance per wallet. It is a planning target, not an exchange quote or a promise of the amount after fees.'],
 ['Name / ticker','Your token’s display name and short symbol. Tickers are not unique identities; the contract address is.'],
 ['Description','A short public description, up to 280 characters.'],
 ['Image / existing image URI','Use a public ipfs:// or https:// image URI. Pro can upload a still PNG, JPEG or WebP up to 4MB. Uploads are public.'],
 ['Website / social links','Optional public links for your project. Enter the full HTTPS website address. Check for typos before launching.'],
 ['Launch configuration','An enabled ETH-paired configuration read from PONS. Review its supply, reserve, graduation threshold and fees.'],
 ['Developer buy','Optional ETH spent buying tokens in your launch transaction. It is separate from the launch fee and gas. Zero launches without that buy.'],
 ['Fee recipient','Address that receives the creator’s protocol payouts; defaults to the connected launching wallet. Verify the entire address.'],
 ['Creator tax','Optional percentage collected under PONS rules, limited by the current protocol cap. It affects future traders, so disclose it clearly.'],
 ['Slippage','Maximum tolerated execution difference from the reviewed quote. HOODLABS caps launch and node trade slippage at 2%. It is not an extra fee or a guarantee that the transaction will succeed.'],
 ['Enable buyback','Directs part of the creator fee share toward protocol buybacks. Bought tokens vest under PONS rules; they are not simply burned and this does not guarantee price support.'],
 ['Tax exemptions','Addresses excluded from the protocol’s opening snipe protection. These must be chosen at creation; they are not a way to change the token’s supply.'],
 ['PONS token address','The full deployed token contract to trade. A verified successful launch fills this field automatically.'],
 ['Buy amount / sell amount','A custom buy is denominated in ETH; a custom sell is denominated in tokens. Check the unit before clicking.'],
];
export default function Guide() { return <main className={styles.page}>
 <Head><title>How to use HOODLABS · Wallets, funding & launching</title><meta name="description" content="A practical HOODLABS guide: create wallets, fund ETH, bridge to Robinhood Chain, configure a PONS launch and manage token balances." /></Head>
 <nav><a href="/">← HOODLABS</a><a href="/pro">Why Pro?</a><a href="/security">Security & recovery</a></nav>
 <header><p className={styles.eyebrow}>THE HOODLABS GUIDE</p><h1>From your first wallet to your first launch.</h1><p>Start with one wallet and a small budget. Follow the network and balance checks at each stage before expanding to more wallets.</p></header>
 <aside className={styles.contents} aria-label="Guide contents">{[['wallets','1. Create wallets'],['funding','2. Fund with ETH'],['bridge','3. Bridge to Robinhood'],['inputs','4. Understand the inputs'],['launch','5. Launch a token'],['trade','6. Buy and sell'],['recovery','7. Recover safely']].map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</aside>
 <section id="wallets"><h2>1. Create and verify node wallets</h2><p>A node here is a wallet address, not a blockchain validator. Free launching uses your connected wallet. The generated-wallet workspace is a Pro tool, available after live services are enabled.</p><ol><li>Open Node wallets and choose a count. Start with one to learn the process.</li><li>Enter a strong backup password and select Generate wallets. Download the encrypted backup.</li><li>Use Restore backup with that file and password. The addresses must match before the app enables signing.</li><li>Keep an offline backup and record which browser/device you use. Lock wallets when finished; inactivity locks the session after 15 minutes.</li></ol><p>Multiple wallets help separate project budgets, test a workflow with a limited balance, and manage distinct treasury or operational allocations. They also multiply gas, withdrawal fees, recovery records and mistakes. Addresses generated from one root share a backup: compromising that root compromises all of them. Multiple wallets do not make activity anonymous or represent independent investors.</p></section>
 <section id="funding"><h2>2. Fund each wallet with native ETH</h2><p>For the bridge supported here, the starting asset is <strong>native ETH on Ethereum mainnet (chain 1)</strong>. The same 0x address can exist on many EVM networks; an identical address does not mean the funds are on the right chain.</p><ol><li>Copy each verified node address. Keep the node number and address together in your funding plan.</li><li>In your exchange, select ETH withdrawal and the Ethereum/ERC20 network. Check the exchange’s actual network name, withdrawal minimum, fee and any address-whitelist delay.</li><li>Send a small test withdrawal first. Wait for the Ethereum balance to arrive before funding additional nodes.</li><li>Fund enough for the bridge amount <em>plus Ethereum gas</em>. A later Robinhood transaction also needs ETH on Robinhood Chain.</li></ol><p>Kraken, Binance, OKX and Bybit expose funding APIs, but availability depends on the account, country, permissions and approved destinations. API credentials belong in the local companion, never on this public website. If your account cannot use API withdrawals, use the exchange’s own withdrawal screen. A connection check is not proof that a real withdrawal will succeed.</p><p>The wallet target balance/CSV is a Robinhood balance plan. Do not import it as an exchange network instruction. Use an explicitly labelled Ethereum funding plan for the source side of a bridge.</p><p><a href="/exchanges">Exchange setup and connection status →</a></p></section>
 <section id="bridge"><h2>3. Bridge Ethereum ETH to Robinhood ETH</h2><ol><li>Choose the funded node in its bridge panel.</li><li>Enter the ETH amount to bridge. Keep enough source ETH for the displayed Ethereum gas reserve.</li><li>Request a Relay quote. Check source Ethereum, destination Robinhood Chain 4663, native ETH, the recipient node, minimum received amount and all estimated costs.</li><li>Review and submit once. Keep the tab and recovery record while the bridge is pending.</li><li>Refresh status until completion is verified, then refresh the Robinhood balances before buying.</li></ol><p>This is a cross-chain transfer, not an ordinary ETH/WETH wrap. WETH is a token and cannot pay native gas directly. An expired quote needs a new quote; an unknown submitted bridge needs status recovery, not another submission.</p></section>
 <section id="inputs"><h2>4. What each input means</h2><div className={styles.table}><table><thead><tr><th>Input</th><th>Meaning</th></tr></thead><tbody>{fields.map(([name,meaning])=><tr key={name}><th scope="row">{name}</th><td>{meaning}</td></tr>)}</tbody></table></div><p>Protocol-specific buyback, fee and exemption rules come from the <a href="https://docs.ponsfamily.com/v2" target="_blank" rel="noreferrer">official PONS V2 documentation</a>. Live on-chain terms take precedence over examples in a guide.</p></section>
 <section id="launch"><h2>5. Launch your token</h2><ol><li>Connect the wallet that will create the token and switch to Robinhood Chain. Ensure it has launch-fee, optional developer-buy and gas funds.</li><li>Complete the public token details, image URI and configuration. Open advanced settings only when you understand their effect.</li><li>Select Review launch. Read the simulation, token details, exact spend and fee recipient.</li><li>Approve the reviewed transaction in your wallet. Do not edit settings or retry during an unresolved submission.</li><li>Wait for a verified receipt with the required confirmations. The token contract then appears in the trading area.</li></ol><p>If the preview says live launching is disabled, configuration is available but no launch can be submitted. If PONS says the account is not eligible or the configuration is disabled, changing local UI values will not grant protocol access.</p></section>
 <section id="trade"><h2>6. Buy supply and manage each node</h2><p>Verify the full token contract and refresh balances. Each row shows its own ETH and token holdings. A buy percentage is a percentage of that node’s spendable ETH after the gas allowance; a sell percentage is a percentage of its token balance. The presets are 5%, 10%, 25% and 50%.</p><ol><li>Select a preset or enter a custom amount, then check the ETH/token unit.</li><li>Buy max uses spendable ETH and keeps an estimated gas reserve. Sell max uses the token balance; the wallet still needs native ETH for gas and any approval.</li><li>Buy max all / Sell max all process the generated wallets in a controlled sequence. A stale quote, unresolved transaction or failure can stop the remaining nodes.</li><li>If selling requires approval, complete that bounded approval first, then request a fresh sale. Approval alone does not sell tokens.</li><li>Wait for balances to refresh before deciding on the next action.</li></ol><p>Quick trading buttons can submit an action immediately after their checks. They are not a second confirmation dialog. Market impact, protocol fees and gas still apply; a 2% slippage limit does not remove price impact. Buying through several wallets does not create additional demand from other people.</p></section>
 <section id="recovery"><h2>7. When something goes wrong</h2><ul><li><strong>Insufficient ETH:</strong> check the chain and reserve gas on that chain.</li><li><strong>Quote expired:</strong> refresh the quote if nothing has been submitted.</li><li><strong>Pending / unknown:</strong> use status recovery and the recorded explorer transaction; never clear history to force another send.</li><li><strong>Wrong network or runtime:</strong> stop and check the supported deployment. Do not bypass the guard.</li><li><strong>Wallets locked:</strong> restore your encrypted backup. Pending transactions remain pending even after locking.</li><li><strong>Pro unavailable:</strong> refresh account status. Payment redirects alone do not enable access.</li><li><strong>Image rejected:</strong> use a still PNG/JPEG/WebP under 4MB, or an existing public image URI.</li></ul><p><a href="/security">Read the security and recovery limits before using significant funds.</a></p></section>
 </main>; }
export async function getServerSideProps(){return {props:{}};}
