import Head from 'next/head';
export default function Security() {
 return <main style={{maxWidth:800,margin:'50px auto',padding:24,lineHeight:1.7,color:'#e5eadf'}}><Head><title>Security & recovery · Hoodrich</title></Head><a href="/">← Launchpad</a><h1>Your wallets, your responsibility</h1>
 <p>Use your connected hardware or browser wallet for free token launching. Hoodrich never asks for that wallet’s seed phrase.</p>
 <h2>Generated wallets</h2><p>Pro wallets are generated and unlocked in this browser. A verified encrypted backup is required before using them. Anyone with your backup and password can spend their funds. Save the backup offline and keep its password separately.</p><p>Browser wallet tools still trust the code served by this website, your browser, and its extensions. A compromised website or device can expose unlocked keys. Use a dedicated browser profile, keep only working funds here, and lock wallets when finished. Locking stops new actions; it cannot reverse a transaction already sent.</p>
 <h2>Recover before retrying</h2><p>A pending or unknown transaction may already have been sent. Check its recorded status and explorer receipt; never clear its history just to try again. Keep your original browser profile until every pending action is resolved. Moving a wallet backup to a new domain or device does not move its transaction history or coordinate actions between devices.</p>
 <h2>Accounts & subscriptions</h2><p>Email codes authenticate your Pro account. Session cookies are HttpOnly and expire after one hour. Signing out revokes that session and locks the workspace. Stripe handles card details; the launchpad checks your current subscription before providing managed uploads. Cancelling and other billing settings are available through Manage subscription.</p><p>Browser code is inspectable and can be copied. Pro sells the hosted service and its supported workflow; it does not prevent you from accessing your own wallets outside this application.</p>
 <h2>Public data & providers</h2><p>IPFS artwork is public and may persist even after unpinning. Never upload private files. Blockchain transactions and wallet addresses are public. RPC providers, Relay, and IPFS providers can observe the requests your browser makes. Account email is handled by the configured authentication provider; billing records by Stripe. No exchange credentials or wallet keys belong in account settings.</p>
 <h2>Launch availability</h2><p>Live launching and billing remain off until the operator completes release checks and configures the service. A successful simulation or explorer response is not a guarantee of execution, finality, token value, or protocol safety.</p></main>;
}
export async function getServerSideProps() { return { props: {} }; }
