import Head from 'next/head';
import styles from '../src/components/Guide.module.css';
import { HOODRICH_MINIMUM_FORMATTED } from '../src/lib/pro-access';

export default function Security(){
 return <main className={styles.page}>
  <Head><title>Security & recovery · HOODLABS</title></Head>
  <nav><a href="/">← HOODLABS</a><a href="/guide">How-to guide</a><a href="/pro">Free vs Pro</a></nav>
  <header><p className={styles.eyebrow}>SECURITY & RECOVERY</p><h1>Keep the keys. Limit the damage.</h1><p>Use working funds, verify every network and address, and resolve uncertain transactions before trying again.</p></header>
  <aside className={styles.contents} aria-label="Page contents"><a href="#before">Before using funds</a><a href="#backup">Backups</a><a href="#recover">Recovery</a><a href="#accounts">Accounts</a><a href="#public">Public data</a></aside>
  <section id="before"><h2>Before using funds</h2><ol><li>Use your own connected hardware or browser wallet for a free launch. HOODLABS never needs its seed phrase.</li><li>Use a dedicated browser profile with minimal extensions and only working funds.</li><li>Verify the chain, full address, amount, fee and contract before approving anything.</li><li>Lock generated wallets when finished. Locking prevents new actions; it cannot reverse a sent transaction.</li></ol></section>
  <section id="backup"><h2>Back up generated wallets first</h2><p>Node wallets are generated and unlocked in the browser. The workspace requires a restore-verified encrypted backup before use.</p><ul><li>Save the backup offline and keep its password separately.</li><li>Anyone with both can spend every wallet derived from that root.</li><li>HOODLABS cannot recover a lost backup or password. A lost backup does not refund an accepted generation attempt.</li><li>The browser still trusts the website code, device and extensions while keys are unlocked.</li></ul></section>
  <section id="recover"><h2>Recover before retrying</h2><p><strong>A pending or unknown transaction may already have been sent.</strong> Check its recorded status and explorer receipt before any new action.</p><ol><li>Keep the original browser profile and recovery record.</li><li>Resolve every pending action on the relevant chain or provider.</li><li>Do not clear history or resend merely because a request timed out.</li><li>Moving a backup to another device or domain does not move transaction history or coordinate actions between devices.</li></ol></section>
  <section id="accounts"><h2>Accounts, billing and holder access</h2><div className={styles.cards}><div><h3>Email and subscriptions</h3><p>Email codes authenticate Free and Pro accounts when sign-in is available. HttpOnly session cookies expire after one hour. Signing out revokes the session and locks the workspace. Stripe handles card details; use <strong>Manage subscription</strong> for billing.</p></div><div><h3>HOODRICH verification</h3><p>A short-lived message proves control of one standard wallet for this site and email session. It is not a transaction or approval and sends no private key.</p></div></div><details><summary>Holder verification details</summary><p>At least {HOODRICH_MINIMUM_FORMATTED} $RICH must remain in one wallet on Robinhood Chain; balances across wallets are not combined. The service stores the linked public address, challenge and session proof. One wallet can link to one account. Unlinking removes the link and invalidates outstanding proofs.</p><p>Smart contract and delegated wallets are unsupported for this proof. Managed services check again; the workspace rechecks about every minute and on focus. Account changes or losing Pro eligibility lock the current wallet session without deleting backup files. Free accounts can restore any valid backup. An active subscription can still grant access.</p></details><p>Browser code can be inspected and copied. Pro provides a hosted service and supported workflow; it does not prevent access to wallets elsewhere.</p></section>
  <section id="public"><h2>Know what becomes public</h2><ul><li>Blockchain transactions and wallet addresses are public.</li><li>IPFS artwork is public and may persist after unpinning. Never upload private files.</li><li>RPC, Relay and IPFS providers can observe browser requests.</li><li>The authentication provider handles email; Stripe handles billing records.</li><li>Exchange credentials and wallet keys never belong in account settings or Token Lab plans.</li></ul><p>Live launching and billing remain off until configured and release-checked. A simulation or explorer response cannot guarantee execution, finality, value or protocol safety.</p></section>
 </main>;
}
export async function getServerSideProps(){return {props:{}};}
